blank_issues_enabled: false
issue_templates:
  - name: "✨ Feature"
    description: "새로운 기능 추가"
    labels: ["feature"]
    body: feature_template.yml
  - name: "📋 To-Do List"
    description: "해야 할 일 정리"
    labels: ["todo"]
    body: todo_template.yml
