name: CI/CD to Elastic Beanstalk

on:
  push:
    branches:
      - master    # main 브랜치에 푸시될 때만 실행 (원하는 브랜치로 조정)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 소스 체크아웃
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Java(Gradle) 환경 세팅
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'  # 원하는 버전

      # 3) gradlew에 실행 권한 부여 (리눅스 환경)
      - name: Grant permission for Gradlew
        run: chmod +x gradlew

      # 4) Gradle 빌드 (테스트를 스킵하려면 -x test)
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      # 5) AWS EB에 배포
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          # GitHub에 등록한 Secrets 사용
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

          application_name: ${{ secrets.AWS_EB_APP_NAME }}
          environment_name: ${{ secrets.AWS_EB_ENV_NAME }}

          # 버전 라벨 (원하는 식으로 설정 가능)
          version_label: ${{ github.sha }}

          # 배포할 JAR 경로 (Gradle 빌드 산출물)
          deployment_package: build/libs/ssauc-0.0.1-SNAPSHOT.jar